#!/usr/bin/python

import os
import sys

def new_name(file):
    os.path.splitext(file)
    return '.'.join([os.path.splitext(file)[0],'gif'])

files = sys.argv[1:]

for file in files:
    os.system(f'convert "{file}" "{new_name(file)}"')
